import { ItineraryResponse } from './types';

const itinerary = {
  friday: {
    afternoon: {
      activity: 'Oficina Francisco Brennand',
      address: 'Propriedade Santos Cosme e Damião, s/n, Várzea, Recife - PE',
      average_cost: 'R$ 20',
      latitude: '-8.0415',
      longitude: '-34.9741',
      time: '13:00 - 17:00',
    },
    date_day: '2024-07-26',
    morning: {
      activity: 'Casa da Cultura',
      address: 'Rua Floriano Peixoto, s/n, São José, Recife - PE',
      average_cost: 'Free',
      latitude: '-8.0653',
      longitude: '-34.8788',
      time: '08:00 - 12:00',
    },
    night: {
      activity: 'Manhattan Café Theatro',
      address: 'Rua Francisco da Cunha, 881, Boa Viagem, Recife - PE',
      average_cost: 'R$ 60',
      latitude: '-8.1125',
      longitude: '-34.8944',
      time: '19:00 - 23:00',
    },
  },
  monday: {
    afternoon: {
      activity: 'Instituto Ricardo Brennand',
      address: 'Alameda Antônio Brennand, s/n, Várzea, Recife - PE',
      average_cost: 'R$ 30',
      latitude: '-8.0359',
      longitude: '-34.9583',
      time: '13:00 - 17:00',
    },
    date_day: '2024-07-22',
    morning: {
      activity: 'Jardim Botânico do Recife',
      address: 'Rua Benfica, 1050, Madalena, Recife - PE',
      average_cost: 'Free',
      latitude: '-8.0558',
      longitude: '-34.9161',
      time: '08:00 - 12:00',
    },
    night: {
      activity: 'Bar Central',
      address: 'Rua Mamede Simões, 144, Boa Vista, Recife - PE',
      average_cost: 'R$ 40',
      latitude: '-8.0621',
      longitude: '-34.8798',
      time: '19:00 - 23:00',
    },
  },
  saturday: {
    afternoon: {
      activity: 'Centro Cultural Judaico de Pernambuco',
      address: 'Rua do Bom Jesus, 197, Recife - PE',
      average_cost: 'R$ 10',
      latitude: '-8.0630',
      longitude: '-34.8711',
      time: '13:00 - 17:00',
    },
    date_day: '2024-07-27',
    morning: {
      activity: 'Feira de Artesanato de Boa Viagem',
      address: 'Avenida Conselheiro Aguiar, Boa Viagem, Recife - PE',
      average_cost: 'Free',
      latitude: '-8.1185',
      longitude: '-34.8973',
      time: '08:00 - 12:00',
    },
    night: {
      activity: 'Cachaçaria Carvalheira',
      address: 'Avenida Antônio de Góes, 62, Pina, Recife - PE',
      average_cost: 'R$ 70',
      latitude: '-8.0874',
      longitude: '-34.8914',
      time: '19:00 - 23:00',
    },
  },
  sunday: {
    afternoon: {
      activity: 'Museu Cais do Sertão',
      address: 'Avenida Alfredo Lisboa, s/n, Recife - PE',
      average_cost: 'R$ 10',
      latitude: '-8.0618',
      longitude: '-34.8721',
      time: '13:00 - 17:00',
    },
    date_day: '2024-07-21',
    morning: {
      activity: 'Praia de Boa Viagem',
      address: 'Avenida Boa Viagem, Boa Viagem, Recife - PE',
      average_cost: 'Free',
      latitude: '-8.1207',
      longitude: '-34.8957',
      time: '08:00 - 12:00',
    },
    night: {
      activity: 'Bares na Rua da Moeda',
      address: 'Rua da Moeda, Recife Antigo, Recife - PE',
      average_cost: 'R$ 50',
      latitude: '-8.0647',
      longitude: '-34.8722',
      time: '19:00 - 23:00',
    },
  },
  thursday: {
    afternoon: {
      activity: 'Shopping RioMar',
      address: 'Avenida República do Líbano, 251, Pina, Recife - PE',
      average_cost: 'R$ 50',
      latitude: '-8.0843',
      longitude: '-34.8939',
      time: '13:00 - 17:00',
    },
    date_day: '2024-07-25',
    morning: {
      activity: 'Museu do Homem do Nordeste',
      address: 'Avenida Dezessete de Agosto, 2187, Casa Forte, Recife - PE',
      average_cost: 'R$ 10',
      latitude: '-8.0357',
      longitude: '-34.9150',
      time: '08:00 - 12:00',
    },
    night: {
      activity: 'Pátio de São Pedro',
      address: 'Praça São Pedro, s/n, Recife - PE',
      average_cost: 'R$ 30',
      latitude: '-8.0730',
      longitude: '-34.8776',
      time: '19:00 - 23:00',
    },
  },
  tuesday: {
    afternoon: {
      activity: 'Mercado de São José',
      address: 'Praça Dom Vital, São José, Recife - PE',
      average_cost: 'Free',
      latitude: '-8.0685',
      longitude: '-34.8787',
      time: '13:00 - 17:00',
    },
    date_day: '2024-07-23',
    morning: {
      activity: 'Parque Dona Lindu',
      address: 'Avenida Boa Viagem, s/n, Boa Viagem, Recife - PE',
      average_cost: 'Free',
      latitude: '-8.1274',
      longitude: '-34.8972',
      time: '08:00 - 12:00',
    },
    night: {
      activity: 'Clube Metrópole',
      address: 'Rua das Ninfas, 125, Boa Vista, Recife - PE',
      average_cost: 'R$ 50',
      latitude: '-8.0643',
      longitude: '-34.8820',
      time: '22:00 - 03:00',
    },
  },
  wednesday: {
    afternoon: {
      activity: 'Praça do Marco Zero',
      address: 'Avenida Alfredo Lisboa, s/n, Recife - PE',
      average_cost: 'Free',
      latitude: '-8.0640',
      longitude: '-34.8714',
      time: '13:00 - 17:00',
    },
    date_day: '2024-07-24',
    morning: {
      activity: 'Passeio de Catamarã',
      address: 'Cais das Cinco Pontas, Recife - PE',
      average_cost: 'R$ 50',
      latitude: '-8.0684',
      longitude: '-34.8753',
      time: '08:00 - 12:00',
    },
    night: {
      activity: 'Bodega do Veio',
      address: 'Rua do Amparo, 212, Olinda - PE',
      average_cost: 'R$ 40',
      latitude: '-8.0124',
      longitude: '-34.8543',
      time: '19:00 - 23:00',
    },
  },
};

const extra_activities_based_on_preferred_travel_styles = [
  {
    activity: 'Galo da Madrugada',
    address: 'Avenida Dantas Barreto, s/n, Recife - PE',
    average_cost: 'Free',
    latitude: '-8.0632',
    longitude: '-34.8777',
    time: '09:00 - 15:00',
  },
  {
    activity: 'Noites Pernambucanas',
    address: 'Rua do Bom Jesus, 183, Recife - PE',
    average_cost: 'R$ 50',
    latitude: '-8.0634',
    longitude: '-34.8713',
    time: '20:00 - 02:00',
  },
  {
    activity: 'Parque Dois Irmãos',
    address: 'Rua Dois Irmãos, 527, Apipucos, Recife - PE',
    average_cost: 'R$ 10',
    latitude: '-8.0010',
    longitude: '-34.9161',
    time: '08:00 - 17:00',
  },
];

const accommodations = [
  {
    address: 'Avenida Boa Viagem, 5426, Boa Viagem, Recife - PE',
    average_cost: 'R$ 350',
    latitude: '-8.1271',
    longitude: '-34.9052',
    name: 'Hotel Atlante Plaza',
    type: 'Hotel',
  },
  {
    address: 'Avenida Domingos Ferreira, 683, Pina, Recife - PE',
    average_cost: 'R$ 200',
    latitude: '-8.0805',
    longitude: '-34.8959',
    name: 'Ibis Recife Boa Viagem',
    type: 'Hotel',
  },
  {
    address: 'Rua Miguel Couto, 81, Boa Vista, Recife - PE',
    average_cost: 'R$ 180',
    latitude: '-8.0609',
    longitude: '-34.8893',
    name: 'Pousada Villa Boa Vista',
    type: 'Pousada',
  },
];

const restaurants = [
  {
    address: 'Avenida Fernando Simões Barbosa, 1200, Boa Viagem, Recife - PE',
    average_cost: 'R$ 60',
    latitude: '-8.1250',
    longitude: '-34.9021',
    name: 'Parraxaxá',
    type: 'Regional',
  },
  {
    address: 'Rua Ondina, 141, Pina, Recife - PE',
    average_cost: 'R$ 80',
    latitude: '-8.0875',
    longitude: '-34.8912',
    name: 'Bargaço',
    type: 'Seafood',
  },
  {
    address: 'Praça Joaquim Nabuco, 147, Santo Antônio, Recife - PE',
    average_cost: 'R$ 100',
    latitude: '-8.0612',
    longitude: '-34.8768',
    name: 'Leite',
    type: 'Traditional',
  },
];

export const mocked_response: ItineraryResponse = {
  local_currency: 'BRL',
  budget: 'R$ 2300',
  destination: 'Recife, Pernambuco',
  travel_period: "['2024-07-21', '2024-07-27']",
  preferred_travel_style: [
    'Nightlife',
    'Nature and Wildlife',
    'Festivals/Events',
  ],
  local_currency_symbol: 'R$',
  extra_activities_based_on_preffered_travel_styles:
    extra_activities_based_on_preferred_travel_styles,
  itinerary,
  recommended_accommodations: accommodations,
  recommended_restaurants: restaurants,
};
